// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOdj9aN2DMR4q1q46WCtp_DohdOlEK9AA',
    appId: '1:784528213198:web:6af5c30ad66b3f0dfdbc9f',
    messagingSenderId: '784528213198',
    projectId: 'my-news-c145e',
    authDomain: 'my-news-c145e.firebaseapp.com',
    storageBucket: 'my-news-c145e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4S2YqMCgUMVNQfToFo-5SxJC-kVd5dtI',
    appId: '1:784528213198:android:590327394a974d55fdbc9f',
    messagingSenderId: '784528213198',
    projectId: 'my-news-c145e',
    storageBucket: 'my-news-c145e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAix9ZQt31cO3k66-DWeQXV8tEBt7xvTXs',
    appId: '1:784528213198:ios:0640b8c48c050c66fdbc9f',
    messagingSenderId: '784528213198',
    projectId: 'my-news-c145e',
    storageBucket: 'my-news-c145e.appspot.com',
    iosBundleId: 'com.example.mynews',
  );
}
